apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-webserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR-USER/my-static-webserver-gitops.git'
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
